### ISSUE TITLE
New pypi release

### ISSUE THREAD

**Issue by roelof-groenewald** [minrk/pytest-mpiexec#25]
I would like to use this package in a project but on my system the pytest plugin loading order is problematic leading to an issue with the outdated pip version of this package. The issue is fixed by the recent changes to directly load report-log (#22), so having an updated PyPi release would be awesome!
Thanks in advance!

**Comment by minrk** [comment]
Thanks! Published 0.0.1a2

**Comment by roelof-groenewald** [comment]
Thank you very much!
